### ISSUE TITLE
[Problem] Dir2Dat not hashing all files correctly

### ISSUE THREAD

**Issue by AdamJGilmore** [SabreTools/SabreTools#104]
What version are you using?
SabreTools_net8.0_win-x64_debug 
rolling release 0c65e5b
.NET 8.0.10 Desktop Runtime x64 running on Windows 11 Pro 23H2

**Describe the issue**
When creating a dir2dat of a folder that contains subfolders and zips (every bottom-level folder contains zips), about 40% of the files inside the zips receive incorrect hashes (crc, md5, sha1).  Re-running the same d2d operation on the same set of files will result in mostly the same result, but sometimes other zips will not get processed properly, whereas ones that had problems previously will be OK (never the same dat twice).

Download my environment with the SabreTools rolling release folder and also the test folder I am trying to reproduce (393 MB download):  [MEGA LINK](https://mega.nz/file/bCJ1CbIY#VnY9hDHjoijLWPQqgj0WomFaJp3JhUeeV8MJT9_MERA) 

1. Put the pre-built "Acorn" folder somewhere and add the path to the command. The Acorn folder 
2. put the SabreTools8 rolling release somewhere and point system path to it.
3.  execute the following command:
sabretools.exe d2d -n="Acorn" -out="C:/SabreTools8/_FRESH_DATS" -f="Acorn.xml" "D:\Acorn"
4. sabretools scans all the folders and zips, then creates the dat.
5. take the newly created dat and put in a brand new instance of RomVault that has no memory of anything.
6. add the Acorn folder as a locked ToSort and do a L3 full scan of the folder
7. add the dat to the datroot and set a new path to rebuild the set to (somewhere different than the Acorn folder)
8. do a find fixes and note the discrepancies with all the unmatched files that have different hashes vs. what is in the original folder.

**Expected behavior**
I expect the dir2dat function to properly hash all files in each of the zips that are scanned and I expect the datfile that gets put into RomVault to be able to rebuild all the files that were scanned to a new location.

**Screenshots**
logfiles are included since with this issue, a screenshot doesn't really show anything as the datfile is created "successfully"

**Comment by mnadareski** [comment]
I have been able to validate this issue is occurring locally as well on the latest build. The symptom is strange, since it will grab the correct hashes the the majority of files, but some small amount just appear to fail to hash fully. I will take a sample of these to see if the hash being calculated is a subset of the data or not.

**Comment by mnadareski** [comment]
The issue was in the hashing library, but only affected compressed files. To make things more frustrating, the values being output were never actually consistent when it failed. To be extremely specific, the issue was if a 0-byte block (usually the last one) was sent to the hashers, it would occasionally freak out if the original data was from a compression stream (or any other non-seekable stream). By rewriting it to avoid ever attempting to hash those 0-byte blocks, I was able to avoid the issues.

In the middle of the testing, I was also finally able to reproduce this intermittent bug in the Hashing library tests. Those minimal examples I had setup made it much easier to narrow it down. Some of the things I thought it would be, like parallel processing of the same block wasn't the issue.
