### ISSUE TITLE
[Request] Add a compression type option to machine

### ISSUE THREAD

**Issue by johnsanc314** [SabreTools/SabreTools#16]
Add a compression type option to the machine which could be used in the future by rom managers like RomVault. This would be useful for mame extras and other sets that do not currently have dats (E.g. eXo)

Example: file, 7z, zip, rar

**Comment by mnadareski** [comment]
Just need to figure out a standardized name for the field then add it to the relevant extensible formats like XML and CMP.

**Comment by mnadareski** [comment]
@johnsanc314 by any chance has GordonJ implemented such a field in RomVault yet? If so, then I can add this to the relevant DAT types.

**Comment by mnadareski** [comment]
Has there been any news on if this has been implemented yet? If not, then I'll just keep this open still.

**Comment by mnadareski** [comment]
I am closing this request as RomVault has not implemented this nor is there any indication it will be.

**Comment by Europia79** [comment]
i'm not familiar with his specific use-case scenario, but this sounds like a classic "Chicken & Egg" situation.

Ultimately, it's just key-value pairs:  It's not like it would actually break anything by having extra information.

Like, **SabreTools** does have a really cool option, `--add-date`:  Does anyone implement support for that ?

But really, with a plethora of libraries out there, anyone can create a custom tool to read any particular key-value pair in the DAT file.

Altho, like i said:  I'm not fully understanding his ultimate purpose ?

But if i understand correctly, he wants to query: *"What compression does this Set use ?"*
...instead of having to query a particular game first in order to get its compression type:
...which is normally the same for the whole Set ?

It's a valid query & a nice feature, imo.

Altho, where he has `compression-type` "file":  That should probably be empty or `none` ?

**Comment by mnadareski** [comment]
This was a case where the original design was being done from the management side and I was trying to be on the forefront of supporting it when it came out. It's been multiple years since and it's no longer a priority to include different archive formats in a single DAT. If it ever comes to fruition from the management side, I'll gladly implement it here.

**Comment by Europia79** [comment]
i'm not familiar with his specific use-case scenario, but this sounds like a classic "Chicken & Egg" situation.

Ultimately, it's just key-value pairs: It's not like it would actually break anything by having extra information.

Like, SabreTools does have a really cool option, `--add-date`: Does anyone implement support for that ?

But really, with a plethora of libraries out there, anyone can create a custom tool to read any particular key-value pair in the DAT file.

Altho, like i said: I'm not fully understanding his ultimate purpose ?

But if i understand correctly, he wants to query: "What compression does this Set use ?"
...instead of having to query a particular game first in order to get its compression type:
...which is normally the same for the whole Set ?

It's a valid query & a nice feature, imo.

Altho, where he has `compression-type` "file": That should probably be empty or "none" ?
