### ISSUE TITLE
Creating update(diff) dats for sets containing multiple dats (like VGM)

### ISSUE THREAD

**Issue by edc71** [SabreTools/SabreTools#74]
I am trying to create a diffdat between vgm 20220131 and 20220218. Have 2 dirs (20220131 and 20220218 obviously)

Tried `SabreTools.exe ud -dc -sf`, `SabreTools.exe ud -dc` with `-out=VGM_DIFF\`

Result was almost the complete set, only the 1st dat parsed (amstrad in this case) was ommitted.

Currently running `SabreTools.exe ud -di` and it seems to be working, but performance is *cough* shite

**Comment by mnadareski** [comment]
With regards to the cascaded diffs:
My understanding is that a good number of the files would be the same between the two input directories, so the outputs will likely be light. Unfortunately, due to how the `--skip-first` flag works, it anticipates that all of the inputs are the same or similar and literally only skips outputting the first file. So the behavior you're seeing there is accurate to what I'd expect.

I don't fully understand by what you're expecting on the output in this particular case. I'd expect that most of the files are there on output, but only with the files filtered out. I will probably have to reach out to you and test locally to see if the code is doing what I'd expect or not.

With regards to the snarky comment around performance, I'm open to performance improvement PRs :)

**Comment by edc71** [comment]
update:

it seems that ud -dc doesnt take in account multiple dats (in this case its a few 100 dats per set)

solution now is merge to superdat for the sets to compare, and run a up -di on them. did not try up -dc -sf, might be faster.. but imo ud -dc -sf should be able to run on dirs with multiple dats

**Comment by mnadareski** [comment]
As mentioned offline, I could not replicate the issue that was being seen above. Just waiting on a test with the latest WIP and the full massive DAT set that triggered this originally.

**Comment by edc71** [comment]
tested with wip version from appveyor (02-22).. results are the same.

PM'd datset and result from conversion to superdat before diffing.
