### ISSUE TITLE
Add cloneof tags

### ISSUE THREAD

**Issue by freitagdavid** [SabreTools/SabreTools#9]
So after playing around with your tool a bit. (Keep up the work on rombasharp I'm super excited for a utility like that.) I decided to try and code my own little utility that would find games that had duplicate crcs of other games and add a cloneof tag to all but one of them. Basically making a crude parent/clone set my main use for this would be the ps1 set which is around 2tb sadly I have found that I do not have the skill. Do you think it would be possible for something along these lines to be implemented. Or is it already possible and I'm just overlooking it. All I found was dedup but that didn't seem to do what I wanted.

**Comment by mnadareski** [comment]
You would be right in thinking that there is no current functionality that will add `cloneof` tags to an existing DAT.

There are a couple of situations that might come up for "automated cloneof":
- Parent/clone sets with single files in each set - this one would not be handled by something like hash matching
- Parent/clone sets with multiple files in each set - similar to something like MAME; the issue that would arise in a case like this is that multiple sets could vie for being "parent" if there are no existing `cloneof` tags. It's also possible that if you have things like a disc-based set that uses audio tracks, you would run into things like demo discs possibly being "parents" to full releases, if they come up in the sort order first.

It sounds, however, that you're more looking into being able to save space via deduplication while still having full sets. The deduplicate functionality that you tried removes copied files, but each set will appear "incomplete" due to this. There are external programs such as Romba (which RombaSharp is based on) and RomVaultX which use file-level deduplication and then either a) rely on the user to rebuild the sets they want (Romba approach) or use a virtual drive to display the sets in full (RVX approach). These are all of your current options, sans finding something else that works for you.

If you do wish to use SabreTools' code in your tool, feel free, but I would appreciate attribution where relevant. And if you wish to contribute to SabreTools through adding this functionality if you find a satisfactory way of doing that, please open a pull request and I'll take a look.

**Comment by freitagdavid** [comment]
Yeah I've looked into Romba as well. I had heard about romvaultx around some forums and found the old repo on github at least it looks quite old since both it and the standard romvault under that username hadn't been updated in quite some time. Do you know of a source for that besides the old repo google has not worked for me on that front. Or is that something that is still in limited alpha testing?

**Comment by freitagdavid** [comment]
Nevermind I just found the fork of romvaultx that you are working on. Keep up the good work man it's always nice having someone contributing a small community like ours.
